
const root=document.documentElement,themeBtn=document.getElementById('themeBtn'),saved=localStorage.getItem('dkane-theme');
if(saved){root.setAttribute('data-theme',saved);if(themeBtn)themeBtn.textContent=saved==='light'?'☀':'☾'}
themeBtn?.addEventListener('click',()=>{const n=root.getAttribute('data-theme')==='light'?'dark':'light';root.setAttribute('data-theme',n);themeBtn.textContent=n==='light'?'☀':'☾';localStorage.setItem('dkane-theme',n)});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const progress=document.getElementById('scrollProgress');addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h?scrollY/h*100:0)+'%'});
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')});
const tilt=document.getElementById('tiltCard');if(tilt){tilt.addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg)`});tilt.addEventListener('pointerleave',()=>tilt.style.transform='')}
const phrases=['building perception systems...','debugging hardware ↔ software boundaries...','shipping AI from model to system...','writing lab notes for future prototypes...','maintaining a private public technical identity...'];let pi=0,ci=0,del=false;const typing=document.getElementById('typing');
function typeLoop(){if(!typing)return;const p=phrases[pi];if(!del){typing.textContent=p.slice(0,ci++);if(ci>p.length){del=true;setTimeout(typeLoop,1100);return}}else{typing.textContent=p.slice(0,ci--);if(ci<0){del=false;pi=(pi+1)%phrases.length;ci=0}}setTimeout(typeLoop,del?24:48)}if(typing)typeLoop();
const command=document.getElementById('command'),search=document.getElementById('commandSearch');function openCommand(){command?.classList.add('open');setTimeout(()=>search?.focus(),20)}function closeCommand(){command?.classList.remove('open');if(search)search.value='';document.querySelectorAll('.command-item').forEach(i=>i.style.display='flex')}window.openCommand=openCommand;
document.getElementById('commandBtn')?.addEventListener('click',openCommand);command?.addEventListener('click',e=>{if(e.target===command)closeCommand()});document.addEventListener('keydown',e=>{if((e.key==='/'||(e.ctrlKey&&e.key.toLowerCase()==='k'))&&!command?.classList.contains('open')){e.preventDefault();openCommand()}else if(e.key==='Escape')closeCommand()});document.querySelectorAll('.command-item').forEach(i=>i.addEventListener('click',()=>{const go=i.dataset.go;closeCommand();if(go.startsWith('http'))window.open(go,'_blank');else location.href=go}));search?.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();document.querySelectorAll('.command-item').forEach(i=>i.style.display=i.innerText.toLowerCase().includes(q)?'flex':'none')});
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{const g=btn.dataset.group,v=btn.dataset.filter;document.querySelectorAll(`[data-group="${g}"] [data-filter]`).forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll(`[data-item-group="${g}"]`).forEach(item=>item.style.display=(v==='all'||item.dataset.tags.includes(v))?'block':'none')}));
document.querySelectorAll('.copy-btn').forEach(btn=>btn.addEventListener('click',async()=>{const pre=btn.closest('.codeblock')?.querySelector('pre');if(!pre)return;await navigator.clipboard.writeText(pre.innerText);const old=btn.textContent;btn.textContent='已复制';setTimeout(()=>btn.textContent=old,1200)}));
